# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.product:
        class: App\Admin\ProductAdmin
        calls:
            - [addChild, ['@admin.stock_entry', 'inventory.product']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Product, controller: App\Controller\ProductAdminController, manager_type: orm, group: Product, label: Product, on_top: true }

    admin.stock_entry:
        class: App\Admin\StockEntryAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\StockEntry, controller: App\Controller\StockEntryAdminController, manager_type: orm, group: admin, label: StockEntry }
